name: Build

on:
    workflow_dispatch:
    push:
        branches: ["master", "develop"]
    pull_request:
        branches: ["master", "develop"]

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.x
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build -c Release --no-restore
            - name: Test Debug
              run: dotnet test -c Debug --no-restore --verbosity normal
            - name: Test Release
              run: dotnet test -c Release --no-restore --verbosity normal
